services:
  test:
    image: pytorch/pytorch:2.1.0-cuda12.1-cudnn8-runtime
    command:
      [
        "python3",
        "-c",
        "import torch; print(torch.cuda.get_device_name(0) if torch.cuda.is_available() else 'No GPU detected')",
      ]
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
